# Generated by Django 3.2 on 2021-04-27 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='BloodGroup',
            new_name='bloodgroup',
        ),
    ]
